### ISSUE TITLE
Automatically account for Daylight Savings Time in time zones that support it.

### ISSUE THREAD

**Issue by lightmaster** [lightmaster/Meteobridge-Weather34-Template#12]
**Is your feature request related to a problem? Please describe.**
Time offset does not automatically adjust for Daylight Savings Time

**Describe the solution you'd like**
Time offset settings automatically adjusts for Daylight Savings Time

**Describe alternatives you've considered**
Alternative - having to remember to adjust time offset for Daylight Savings Time

**Additional context**

I've always hated these one size fits all issues templates, lol

**Comment by weather34** [comment]
valid point now tell how you  would deal with same all year round and still php not recognizing turkey is on same time all year round.. 

you will see this reference  misinformation...

After a year without time changes, Turkey has decided to reintroduce Daylight Saving Time (DST), starting in 2018. On October 28, 2018, clocks in Turkey will be set back 1 hour from 04:00 (4:00 am) to 03:00 (3 am), local time.Oct 31, 2017
which is on timeanddate.com this is incorrect we still stay on UTC +3 all year .. 

ill happily would have introduced any solutions but none ever came forth and as of today im off the radar and look forward to handing over mid april and hopefully by early may support will good again.

ps there is a significant update due sometime later today which also requires a meteobridge reboot to get new API values which now stands at 171 different generated meteobridge values .
