### ISSUE TITLE
Rain graph left axis becomes unreadable if high rain amounts

### ISSUE THREAD

**Issue by dive76** [lightmaster/Meteobridge-Weather34-Template#13]
![2019-03-11](https://user-images.githubusercontent.com/41624349/54188553-e6feb900-44ea-11e9-80b9-5dd475828ce6.png)

During high amount rain events >20mm left axis becomes unreadable.

**Comment by weather34** [comment]
not sure what to make of your graph or readings .. you have 50+mm of rain measured in a hour and rain rate of 170mm .. could be real but notice the 54.8mm of rain last hour.. unfortunately it will have to wait until may till this is resolved ..unless anyone else offers a solution..i.e increase the intervals in the chart scripts ..

**Comment by dive76** [comment]
Hi Brian, no issue. Tropical rain is like this. We sometimes have 80mm in one hour and up to 280mm/h rain rate! Let me have a look in the script. Should be easy to fix.

**Comment by dive76** [comment]
interval set to "auto".



[Rain Graphs.zip](https://github.com/weather34/Meteobridge-Weather34-Template/files/2956223/Rain.Graphs.zip)

**Comment by lightmaster** [comment]
Playing around with this some, I'd say need to set the labelFormatter of both Y axes to have 2 decimal places. At least with inches and a low rain rate, I end up with a chart that has multiple .1in

![img](https://i.imgur.com/JVrMNoF.jpg)

line 126: `interval:'auto',`
line 136-138: `labelFormatter: function ( e ) {`
`         return e.value .toFixed(2) +"<?php echo $rainunit ;?>" ;  `
`         },		 `
line 167-169: `labelFormatter: function ( e ) {`
`         return e.value .toFixed(2) +"<?php echo $rainunit ;?>" ;  `
`         },		 `

**Comment by weather34** [comment]
merged many thanks..brian
