### ISSUE TITLE
Wind Run not working

### ISSUE THREAD

**Issue by nicoloconte** [lightmaster/Meteobridge-Weather34-Template#19]
Hi, 
in my site, wind run isn't working. 

http://www.meteomarianocomense.com/pws/

Thanks a lot. 

Nicolò

**Comment by lightmaster** [comment]
I need to familiarize myself with how the Wind Run calculations work. Let me get back to you on that one when I know more.

**Comment by nicoloconte** [comment]
With latest commits, wind run is now working.
