### ISSUE TITLE
Wind direcrtion graph

### ISSUE THREAD

**Issue by nicoloconte** [lightmaster/Meteobridge-Weather34-Template#21]
Hi, 
is possible to add wind direction graph?

Thanks a lot. 

Nicolò

**Comment by lightmaster** [comment]
This already does exist, however for whatever reason there is no link to it on the main page. I'll add that when I update the other charts soon.

Your's is at http://www.meteomarianocomense.com/pws/mbcharts/todaywinddirection.php

**Comment by nicoloconte** [comment]
@lightmaster great, thanks!
