### ISSUE TITLE
Web Cam Picture Aspect Ratio issue

### ISSUE THREAD

**Issue by dive76** [lightmaster/Meteobridge-Weather34-Template#23]
Hi, with the new design the webcam picture aspect ratio is not maintained. This means picture is distorted depending on window size.

https://www.singaporeweather.info/cam.php

**Comment by dive76** [comment]
Noted your fix. All working well now. Thanks a lot!

**Comment by weather34** [comment]
replace outlookwu.php it had a typo in any values above 27c visible in celsius only as always your climate reveals stuff out of season i was never able too see .. take care brian
