### ISSUE TITLE
Title in graph windows hard to read

### ISSUE THREAD

**Issue by dive76** [lightmaster/Meteobridge-Weather34-Template#24]
Titles in graph windows are very hard to read due to grey letters on dark grey background.
![2019-05-03](https://user-images.githubusercontent.com/41624349/57122657-f692d380-6db0-11e9-8920-7e0bf5f33730.png)

**Comment by dive76** [comment]
clearing browser cache solved it.

**Comment by lightmaster** [comment]
Yup, clearing your cache and cookies are the best thing to do when any website is acting weird. When I first installed the beta from today in place of my main site, it opened all links in a new window, but moving the same folder to a new name and it opened them in the new iframe. A browser clear later and it worked fine.

Also, if something acts weird like that, open your site in a incognito window, no cookies or caches are saved once the window closes, so a fresh incognito session means everything is new in the browser.
