### ISSUE TITLE
Update time of Air Quality keeps showing 07:30am

### ISSUE THREAD

**Issue by dive76** [lightmaster/Meteobridge-Weather34-Template#25]
Update time of Air Quality keeps showing 07:30am but data updates well. 
https://www.singaporeweather.info/
![2019-05-03 (1)](https://user-images.githubusercontent.com/41624349/57135739-163ff100-6ddd-11e9-8aec-049a7138ae0a.png)

**Comment by lightmaster** [comment]
Should be fixed in 9d4691076fa8ac5b0f9150455cfcd3752cc4aa97

**Comment by dive76** [comment]
Great. Working well now.
