### ISSUE TITLE
Windy Map

### ISSUE THREAD

**Issue by gand07** [lightmaster/Meteobridge-Weather34-Template#26]
Possibility to show m/s in the Wind Map.

Rgds
gand

**Comment by lightmaster** [comment]
Figured out changing the Wind speed, however I assume you and anyone else would also like to change Windy's temperature and rain units too. These units seem to be bugged on their site and [I have submitted a bug report with them](https://community.windy.com/topic/8375/can-t-change-temperature-and-rain-units-in-embed-iframes). Soon as they get it fixed, I'll update the url's here and push out the update.

**Comment by lightmaster** [comment]
I went ahead an pushed out the fix in commit eaebdc17c901a58c33b4d7a40a03f28787056172, however until Windy fixes their own bugs, only your wind speed is changeable on their site. The code to change the temperature and rain units is in there and already gets sent to Windy, so it'll start working as soon as they eventually fix it. Someone reported this bug back in Oct 2018 IIRC, so don't hold your breath on those other 2 units.

**Comment by lightmaster** [comment]
Not sure when Windy.com fixed it, but they are now paying attention to Wind Speed and Temperature settings, so it should now show whatever units you use for your site. The rain units are still ignored, however its showing up as in for me now, so perhaps they do it based on one of the other units or regional settings.
