### ISSUE TITLE
Monthly and Yearly Windspeedgust charts

### ISSUE THREAD

**Issue by steepleian** [lightmaster/Meteobridge-Weather34-Template#28]
Strange and excessively high results with the monthly and yearly charts. It appeared that things were being multiplied by a conversion factor rather than being divided.

I changed conversion section near the top section of code for the monthly and yearly charts to this 

$conv = 1;

	if ($windunit == 'mph') {
    $conv= '0.621371';
  } else if ($windunit == 'm/s') {
    $conv= '0.277778';
  } else if ($windunit == 'km/h'){
    $conv= '1';
  }

All seems to be well now. Not sure if this is a bug or differences between realtime data .txt file types.

**Comment by lightmaster** [comment]
Wind speed is pulled from the MB as MB default units,  m/s. Google says to cover m/s to mph, multiply by 2.237.

[![Screenshot-20190512-080021-Chrome-Beta.jpg](https://i.postimg.cc/br5gjWzG/Screenshot-20190512-080021-Chrome-Beta.jpg)](https://postimg.cc/D4qLrC4F)
[![Screenshot-20190512-080103-Chrome-Beta.jpg](https://i.postimg.cc/zB0px36F/Screenshot-20190512-080103-Chrome-Beta.jpg)](https://postimg.cc/jwnz5qsD)
[![Screenshot-20190512-075913-Chrome-Beta.png](https://i.postimg.cc/vH1XvYz5/Screenshot-20190512-075913-Chrome-Beta.png)](https://postimg.cc/56Vw4MDt)

**Comment by steepleian** [comment]
Ok I thought that might be the case. Cumulus defaults to km/h so that
explains the reason. However with WeeWX CRT plug-in I can change the
default to m/s.
Thanks William.
