### ISSUE TITLE
May mounth graphs error

### ISSUE THREAD

**Issue by nicoloconte** [lightmaster/Meteobridge-Weather34-Template#29]
Hi, 
i'm having problem in all May graph. I see several 10 may and a 30 apr. 

![Screenshot_20190512_161507_com android chrome](https://user-images.githubusercontent.com/18371284/57583563-d6aa9080-74d1-11e9-9b70-4ad714446832.jpg)

Thanks for the support!

Nicolò

**Comment by lightmaster** [comment]
Looks like you had the wrong date on your system. Check your date and open 2019.csv and 2019/may.csv and change the dates  to what they should be

**Comment by nicoloconte** [comment]
Ok, I will try. But why?

**Comment by lightmaster** [comment]
Who is the host of your server?

**Comment by nicoloconte** [comment]
Aws

**Comment by weather34** [comment]
end of day not running ?? what appears in yearly for the same period . unless something changed in script both files should show identical error for same period  . take a screenshot of 2019.csv last 10 rows and may.csv in 2019 folder

**Comment by lightmaster** [comment]
Looking at the graphs and all, looks like the end of day and add to year did run at least last night, and the current result.csv has may 12th's date in it. Everything looks like it should run tight tonight, so I'll check your graphs again after your midnight to see what happens.

**Comment by nicoloconte** [comment]
2019.csv
![image](https://user-images.githubusercontent.com/18371284/57604190-db1f8980-7563-11e9-88eb-cbce8c48affd.png)


may.csv
![image](https://user-images.githubusercontent.com/18371284/57604147-bf1be800-7563-11e9-907a-58eca6c83b53.png)

**Comment by lightmaster** [comment]
Those may 10ths, the have the same highs and lows for temp. Did you manually  run addtoyear.php multiple  times that day?

**Comment by nicoloconte** [comment]
Yes, maybe on 10 May due Meteobridge problem. But why 11 may isnt' in the cvs?

Thank you very much for the support.

**Comment by lightmaster** [comment]
For the last may 10th that has some different values, it's probably a mix of may 10th and 11th. The addtoyear script picks the first date in its list (may 10th in this scenario) and uses that as the day, then is uses the max/min for other columns, so if the 11ths maxes were smaller than the 10ths maxes, and the 11ths mins were bigger than the 10ths mins, it's data would hid within the 10ths data.

So, with you MB issues that ran addtoyear.php an couple extra times, it probably didn't run empty.php to clear out the daily file.

Best way I can see you fix your charts now (and what what I would do for mine), is to delete the 2nd 2 may 10th lines.

**Comment by nicoloconte** [comment]
Ok, thanks a lot. I will delete also 30 apr.
