### ISSUE TITLE
Unable to set main station clock to 12 hours

### ISSUE THREAD

**Issue by steepleian** [lightmaster/Meteobridge-Weather34-Template#30]
When selecting 12 in settings (or changing manually), the main station clock remains on 24 hr display format.

**Comment by weather34** [comment]
probably no updated version of updater.php added needs additional code to replaced

try updater.php i just checked it and it works fine from beta repo https://github.com/weather34/Meteobridge-Beta

**Comment by lightmaster** [comment]
I've almost finished a simpler fix for the 12 hour clock that doesn't require a second setting or anything, gimme a couple hours to finish getting am/pm  added to it.

**Comment by lightmaster** [comment]
I've got it the changes to updater.php written, just waiting for 12pm to hit so I can make sure it works for pm

**Comment by steepleian** [comment]
To you want me to check it? It’s 14:37 here.

**Comment by lightmaster** [comment]
Fixed in 8d9d34f
