### ISSUE TITLE
Option to hide DS Hourly Forecast (Hourly Forecast DS instead WU)

### ISSUE THREAD

**Issue by nicoloconte** [lightmaster/Meteobridge-Weather34-Template#32]
Hi boys,
with forecast3wularge.php, the Hourly forecast is from DS. Is it possible to hide or to change the dataprovider?

Thanks.

**Comment by weather34** [comment]
no  unfortunately provider info and credits must always be shown and left intact  . ethics creates collaboration any removal of this type of info you lose support.. sounds harsh but if you read any api provider generally requests some form of accreditation.. 

weather underground api does not provide hourly data in their API hence the darksky option

**Comment by weather34** [comment]
reworking darksky to same wu layout requires a complete rework of css layout..best just use it as it is..the darksky hour option mixed with wu was not a part of the original so this must be a recent addition , is it not optional ?.

**Comment by nicoloconte** [comment]
There has been a misunderstanding, I don't wont to hide credits. I would like to hide the hourly link. In my case WU and DS have very different forecast in some cases.

**Comment by weather34** [comment]
no misunderstanding just making the point .. is the darksky option not available sorry i dont have access to this version on my iPad . but whalt happens if you change the darksky api key to 123456789

**Comment by nicoloconte** [comment]
Black popup

![image](https://user-images.githubusercontent.com/18371284/57621188-18e3d880-758b-11e9-91e4-3586a51715b0.png)

**Comment by weather34** [comment]
sorry perhaps lightmaster will have to answer i recall if wu was used as the forecast data it didnt show any darksky data .. brian

**Comment by lightmaster** [comment]
as of right now, setting dark sky api key to 11111111111111 (default value) will hide it, assuming you don't want any darksky data at all. Gimme a little bit and I'll have a new setting for whether or not to show the darksky hourly forecast, defaulting to yes but you can change it to no.

**Comment by nicoloconte** [comment]
> as of right now, setting dark sky api key to 11111111111111 (default value) will hide it, assuming you don't want any darksky data at all. Gimme a little bit and I'll have a new setting for whether or not to show the darksky hourly forecast, defaulting to yes but you can change it to no.

Ok great, It worked.

**Comment by lightmaster** [comment]
Added in c13c37edd56dc399331c8734dbff69f84e7d7199
