### ISSUE TITLE
fixed easyweathersetup save on error message

### ISSUE THREAD

**Issue by weather34** [lightmaster/Meteobridge-Weather34-Template#36]
this line is causing error on save . 

$nanourl    = "'.$_POST["nanourl"].'";

what is this used for ?? be-careful not all users use NANO(SD) ..

have removed it....brian

**Comment by lightmaster** [comment]
It's an optional variable for future use with downloading nano/pro charts. Doesn't have any use at all yet, just added it now since had to add daughter setting and to keep it from erasing my setting. Not sure why it would cause an error though cuz it's not called yet...

**Comment by weather34** [comment]
ok it requires to parts but think you worked it out but yes it caused a php flag error on line 96 .

have a good day

**Comment by lightmaster** [comment]
Seems it's not too happy with it since it's not set on the settings page. I'll deal with it later though when it's implemented and just set the variable within my downloader script in the mean time.
