### ISSUE TITLE
Moonphase

### ISSUE THREAD

**Issue by spatenchb** [lightmaster/Meteobridge-Weather34-Template#37]
Is the moonphase calculation off a little? I am seeing a Full Moon today (May 20) and I think it should be a Waning Gibbous.

Thanks,

Chuck

**Comment by weather34** [comment]
,from the meteobridge template page unarsegment: lunarphase segment as integer (0 = new moon, 1-3 = growing moon: quarter, half, three quarters, 4 = full moon, 5-7 = shrinking moon: three quarter, half, quarter) https://www.meteobridge.com/wiki/index.php/Templates

meteobridge outputs a value of 4 for today ,according to above 4 is full moon . perhaps it will change at moonrise.. ?? brian

**Comment by lightmaster** [comment]
I think it's mostly a matter of at what point you consider a full moon to be over. My site says 96.5% luminance and calls it full moon, [timeanddate.com](https://www.timeanddate.com/moon/phases/@614427) calls that same amount of luminance to be waning. How luminance needs to decrease before the full moon is considered over...

Either way, the name of it comes from MB.

**Comment by spatenchb** [comment]
After looking into it a little more, it appears that there are only 4 Official Phases. The others are somewhat vague (no well defined percentage). In fact, all 3 of our stations just changed to Waning. So, Boris and Meteobridge have it right!. I think we can close the "Bug"

Thanks guys.
Chuck
