### ISSUE TITLE
homeindoor.php

### ISSUE THREAD

**Issue by steepleian** [lightmaster/Meteobridge-Weather34-Template#38]
Misalignment when viewed with Edge or Firefox browsers on a Windows PC. Chrome is OK.

![image](https://user-images.githubusercontent.com/18438654/58160348-2d545f00-7c76-11e9-88db-0e2260f4aaae.png)

**Comment by weather34** [comment]
hi ian 

will look tonight again probably something small . feel the days of works with one browser not the other coming back..

**Comment by steepleian** [comment]
Hi Brian,
Thanks. I understand that Microsoft are basing their next generation browser on Mozilla, so that may help things in the future. As you know I am a MacOS and Linux man, but I keep a Windows VM for checking,

**Comment by weather34** [comment]
i can not check windows browsers dont own anything windows ..does it break on mac with firefox etc

**Comment by lightmaster** [comment]
> Hi Brian,
> Thanks. I understand that Microsoft are basing their next generation browser on Mozilla, so that may help things in the future. As you know I am a MacOS and Linux man, but I keep a portable Windows machine for checking,

Microsoft Edge is being moved to Chromium, not Mozilla. Least not according to all the articles I've seen.

**Comment by steepleian** [comment]
Brian,
Firefox breaks on MacOS as well, Chrome is OK.

William,
Yes you are right (just getting confused in my old age)!

**Comment by weather34** [comment]
ok will look tonight ..thanks

**Comment by lightmaster** [comment]
> William,
> Yes you are right (just getting confused in my old age)!

I know Microsoft is de-Googlizing chromium and adding their own services, but hopefully they won't muck about with the CSS processing. Then there will *only* be 3 different browsers to worry about.

**Comment by lightmaster** [comment]
Brian's changes in 79859d07c649b2bb6162f92923ded9c42f2e40ca seem to have fixed this on Windows Firefox for me. Everything look good for you now?

**Comment by steepleian** [comment]
All fine here in all browsers on all platforms.

Thanks

**Comment by spatenchb** [comment]
I agree. Looks like Brian's changes fixed this issue.

Thanks,
