### ISSUE TITLE
Almanac Charts on Mobil

### ISSUE THREAD

**Issue by spatenchb** [lightmaster/Meteobridge-Weather34-Template#39]
Prior to this latest update (5/21/19), a "touch" on a Almanac Chart would bring up a popup box with Date, Hi and Low data points. The popup still works on the desktop (via mouse), but does not work on Mobil (Iphone/Ipad).

Thanks,

Chuck

**Comment by lightmaster** [comment]
I've been meaning to check that out. Seems that mobile has an issue with displaying both cross hairs and the tooltip. If I can't find a fix to CanvasJS for it, will probably have to turn off one or the other..

**Comment by weather34** [comment]
im confused can we have some screenshots of whats missing 

i alwys use ipad as tool to crosscheck see below with tooltips a

![tooltip](https://user-images.githubusercontent.com/20555738/58188015-96f95b00-7cc0-11e9-83f3-1e68795b4801.png)

**Comment by spatenchb** [comment]
![695DF5A6-A8AF-4065-A4F3-1C093B78F655](https://user-images.githubusercontent.com/49997482/58189287-3817ef80-7c88-11e9-90af-2a4ffe963cba.png)
Brian,

It works on your site. If you go to William's site and click on Wind for the month of May - the Tooltip box does not display on Ipad. It still works correctly on my site because I have not updated to the latest commit (Yesterday).

Chuck

**Comment by lightmaster** [comment]
Very peculiar. On Android, it works perfectly in portrait, but in landscape the bottom crosshair date doesn't move after a certain point

![Screenshot_20190522-115510_Chrome Beta](https://user-images.githubusercontent.com/5307827/58189464-8c22d400-7c88-11e9-9802-923ebd7b9570.png)
![Screenshot_20190522-115537_Chrome Beta](https://user-images.githubusercontent.com/5307827/58189473-904ef180-7c88-11e9-86ad-d437c3ecf77a.png)

**Comment by lightmaster** [comment]
And now I pulled my site back up and it's working fine again in landscape and portrait

**Comment by lightmaster** [comment]
Actually, on Android at least, the crosshairs seem to bug out only when the chart is opened portrait, and then rotated to landscape with the chart still open. The crosshairs then won't go past past a point that looks to be the width of the chart in portrait mode.

**Comment by weather34** [comment]
ok i found it , william that tooltip script you compiled is really complex revert to back to something near the original just have a dark barkground for tooltip and fixed font color .its a lot of complex code  ..im on a desktop and wind almanac is what i used to find  missing tootip  .rain ,barometer,wind,temperature almanacs have all missing tooltips in desktop .

also animation really lags on the iPad mini but ok on iPad Air2/Pro

![3](https://user-images.githubusercontent.com/20555738/58190127-84812080-7cc4-11e9-8e18-c0013fb97e01.jpg)




toolTip:{
			   fontStyle: "normal",
			   cornerRadius: 4,
			   backgroundColor: "<?php echo $tooltipbackgroundcolor;?>",	
			   fontColor: "#aaa",			   	
			   fontSize: 11,	   
			   toolTipContent: " x: {x} y: {y} <br/> name: {name}, label:{label} ",
			   shared: true, 
 },

**Comment by spatenchb** [comment]
William,
I thought it might be a caching issue. I cleared cache on Safari (Ipad) and went back to your May Wind chart and it does not shown the tip box.

**Comment by lightmaster** [comment]
> toolTip:{
> fontStyle: "normal",
> cornerRadius: 4,
> backgroundColor: "",
> fontColor: "#aaa",
> fontSize: 11,
> toolTipContent: " x: {x} y: {y} 
> name: {name}, label:{label} ",
> shared: true,
> },

I'll take a look at it. Also, toolTipContent is not used there at all cuz shared is turned on.

**Comment by lightmaster** [comment]
> ok i found it , william that tooltip script you compiled is really complex revert to back to something near the original just have a dark barkground for tooltip and fixed font color .its a lot of complex code ..im on a desktop and wind almanac is what i used to find missing tootip .rain ,barometer,wind,temperature almanacs have all missing tooltips in desktop .

The tooltips work fine on my Windows computer. But the crosshairs act a little weird. I'm gonna disable the crosshairs on my monthly wind chart, let me know if the tooltip works fine on it in Mac.

**Comment by lightmaster** [comment]
Clear cache just to be careful

**Comment by spatenchb** [comment]
I have done some testing using William's Site. I cleared cached on all browsers - here are the results.
Monthly Temperature Module (with Crosshairs disabled):
Windows Desktop:
Chrome - Tooltip only
Firefox - No Tooltip, No Crosshairs
Edge - No Tooltip, No Crosshairs

Ipad Pro/Ipad Mini: Animation a little slow on Ipad Mini
Safari, Chrome, Firefox - No Tooltip, No Crosshairs

Mac Desktop:
Safari - No Tooltip, No Crosshairs
Chrome - Tooltip Only, No Crosshairs

I also checked the present Monthly Temperature Module (crosshairs still enabled):

Windows Desktop:
Chrome - Tooltip and Crosshairs Working
Firefox - No Tooltip, No Crosshairs
Edge - Tooltip and Crosshairs both working

Ipad Pro/Ipad Mini: Animation a little slow on Ipad Mini
Safari, Chrome, Firefox - No Tooltip, Crosshairs Working

Mac Desktop:
Safari - No Tooltip, Crosshairs Working
Chrome - Tooltip and Crosshairs Working

**Comment by lightmaster** [comment]
Check again. There's an issue with CanvasJS's CanvasJS.formatDate function, which incidentally wasn't even needed. Removing that function from all the charts seems to have gotten it working on Firefox and chrome on Windows for me. Lemme know if it's still broken on anything else. All charts are changed on mine to have that function removed.

**Comment by spatenchb** [comment]
William,

I retested all of those listed above and they are now all working correctly. Look like that fixed it.

Thanks,

Chuck

**Comment by lightmaster** [comment]
K. I'll push the fix then
