### ISSUE TITLE
Temperatureyear.php Module - Max Value

### ISSUE THREAD

**Issue by spatenchb** [lightmaster/Meteobridge-Weather34-Template#43]
I just noticed that the temperatureyear module (top) is reporting a different MAX Year value (87.8 F) than the Almanac (88.2 F) and Graph. In looking at the data files, it appears that the Almanac value is correct. The dates are the same.

![Capture](https://user-images.githubusercontent.com/49997482/58332936-51e14000-7e0a-11e9-9afd-cbbc022f98bb.PNG)

**Comment by weather34** [comment]
try it now temperatureyear.php 

sent from iPad

**Comment by spatenchb** [comment]
That fixed it Brian.

Cheers!

Chuck
