### ISSUE TITLE
Demande nano-sd

### ISSUE THREAD

**Issue by neomanu16** [lightmaster/Meteobridge-Weather34-Template#44]
Hello, Following the concern of the Cumulus version that today "hui I still have concerns about the amount of rain.
I have the idea of ​​buying a nano-sd can help me tell me who should I really buy to be able to benefit from the same version as you ...
a link of the purchased material would be welcome.
Thank you in advance...
Best regards,
Emmanuel

**Comment by lightmaster** [comment]
If I'm understanding you correctly, you're saying you want to buy a Nano SD, correct? What country are you located in then?

Seeing as this is not an actual issue with the site, I'm going to go ahead and close this issue, however feel free to continue replying to it.

**Comment by neomanu16** [comment]
HI I am in France here is my site for me located
http://www.meteo16-vars.com/
