### ISSUE TITLE
Wind Module

### ISSUE THREAD

**Issue by gand07** [lightmaster/Meteobridge-Weather34-Template#46]
Hi 
Is it possible to bring this back from Lightmaster:

_I just pushed out a fix to the Wind Module that changes the left speed to be the current wind speed as of when your MB last sent data to your site, and the right speed is now actually reading the gust speed. Previously, gust speed had been the instantaneous speed, now it is the max speed within the last 10 minutes_

gand

**Comment by lightmaster** [comment]
Yea, should be able to bring this back. It got overwritten a while back and nobody complained, so I just left it as is. Not sure if I'll be able to get to it tonight, but I will soon as I can.

**Comment by gand07** [comment]
Thanks

**Comment by lightmaster** [comment]
Added back now
