### ISSUE TITLE
Webcam Type Support

### ISSUE THREAD

**Issue by chrismaltese** [lightmaster/Meteobridge-Weather34-Template#47]
Tried to enter http://23.24.167.243/cam as a live cam URL, but it won't work.  Adding here as possible candidate for inclusion.

**Comment by lightmaster** [comment]
Manufacturer?

**Comment by chrismaltese** [comment]
I honestly don’t know. It’s a link of a camera near my house. I’ll do some research.

**Comment by chrismaltese** [comment]
Unable to identify vendor.
