### ISSUE TITLE
Parse error in windyradar.php

### ISSUE THREAD

**Issue by gand07** [lightmaster/Meteobridge-Weather34-Template#58]
Hi 
After the latest update, I get this:

Parse error: syntax error, unexpected 'echo' (T_ECHO) in /var/www/lynghuzed.dk/public_html/windyradar.php on line 1

Any clues?

Rgds
Gert
https://lynghuzed.dk

**Comment by lightmaster** [comment]
Accidentally typed "pho" instead of "php". Not sure why my site didn't throw an error on it, but it's fixed now. Feel free to reopen this if you see anything else I screwed up with Commit 4207220

**Comment by gand07** [comment]
Hi

 

Working perfect now. Thanks.

 

Gert

 

Fra: lightmaster <notifications@github.com> 
Sendt: Thursday, 15 August 2019 11.51
Til: lightmaster/Meteobridge-Weather34-Template <Meteobridge-Weather34-Template@noreply.github.com>
Cc: gand07 <ga@gand.dk>; Author <author@noreply.github.com>
Emne: Re: [lightmaster/Meteobridge-Weather34-Template] Parse error in windyradar.php (#58)

 

Accidentally typed "pho" instead of "php". Not sure why my site didn't throw an error on it, but it's fixed now. Feel free to reopen this if you see anything else I screwed up with Commit  <https://github.com/lightmaster/Meteobridge-Weather34-Template/commit/4207220a0f9116f111aac1d628cf1d1b4c74ccf9> 4207220
