### ISSUE TITLE
[Feature Request] Change months/years on charts

### ISSUE THREAD

**Issue by lightmaster** [lightmaster/Meteobridge-Weather34-Template#7]
Can you add arrows to the sides of the Year and Month charts so you can browse through previous months and years?

**Comment by weather34** [comment]
hi probably not at the moment its no a bad idea its a good idea but im just now adding additional stuff where its easy to implement without much additional code or re writing .unless you have a working understable clean solution it wont perhaps in May who knows ..sorry..brian (somewhat braindead these days just doing the easy things) ..

**Comment by lightmaster** [comment]
I understand. Figured it would be done by whoever takes it up after you, just wanted to go ahead and put it out there before I forgot, lol
